---
title: Salomão Avalia
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: eliel
    avatar: "/assets/images/avatar1.jpg"
- scope:
    path: _pages
  values:
    layout: page
name: Salomao Avalia
description: Salomão Avalia é o site do avaliador de imóveis Eliel Salomão.
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
baseurl: 
include:
- _pages
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
- jekyll-admin
authors:
  eliel:
    name: Eliel
    site: https://www.salomaoavalia.com.br
    avatar: "/assets/images/avatar1.jpg"
    bio: Olá, meu nome é Elie Salomão, sou avaliador de imóveis. Seja bem-vindo ao meu site, espero que eu possa ajudar
      a encontrar o melhor imóvel para seu investimento ou para a realização do seu sonho!
    email: eliel@salomaoavalia.com.br
    twitter: https://twitter.com/salomaoavalia
markdown: kramdown
highlighter: rouge
paginate: 10
exclude:
- README.markdown
- package.json
- grunt.js
- Gruntfile.js
- Gruntfile.coffee
- node_modules
