---
title: Salomaoavalia
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: eliel
    avatar: "/assets/images/avatar1.jpg"
- scope:
    path: _pages
  values:
    layout: page
name: Salomao Avalia
description: Salomão Avalia é o site do avaliador de imóveis Eliel Salomão.
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
baseurl: 
include:
- _pages
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
- jekyll-admin
authors:
  sal:
    name: Eliel
    site: https://www.salomaoavalia.com.br
    avatar: "/assets/images/avatar1.jpg"
    bio: Olá, meu nome é Eliel. Seja bem-vindo ao meu site, espero que eu possa ajudar a realizar o seu sonho!
    email: eliel@salomaoavalia.com.br
    twitter: https://twitter.com/salomaoavalia
  # jane:
  #   name: Jane
  #   site: https://www.wowthemes.net
  #   avatar: "/assets/images/avatar2.jpg"
  #   bio: Blogger, fashionista, love to explore new ideas and write on my morning coffee!
  #   email: fakemail@gmail.com
  #   twitter: https://twitter.com/wowthemesnet
markdown: kramdown
highlighter: rouge
paginate: 10
exclude:
- README.markdown
- package.json
- grunt.js
- Gruntfile.js
- Gruntfile.coffee
- node_modules
